# Generated by Django 5.0.3 on 2024-05-07 19:10

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('biographia', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(upload_to='users')),
                ('instagram', models.CharField(blank=True, default='#', max_length=200, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, default='#', max_length=200, null=True, verbose_name='Facebook')),
                ('tiktok', models.CharField(blank=True, default='#', max_length=200, null=True, verbose_name='Tik Tok')),
                ('telegram', models.CharField(blank=True, default='#', max_length=200, null=True, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, default='#', max_length=200, null=True, verbose_name='WhatsApp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'permissions': [('can_view_profile', 'Pode Ver Perfil'), ('can_change_profile', 'Pode Atualizar Perfil'), ('can_add_profile', 'Pode Adicionar Perfil'), ('can_delete_profile', 'Pode Deletar Perfil')],
            },
        ),
    ]
