# Generated by Django 5.0.3 on 2024-12-19 17:57

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('biographia', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(upload_to='users')),
                ('instagram', models.CharField(blank=True, default='#', max_length=200, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, default='#', max_length=200, null=True, verbose_name='Facebook')),
                ('tiktok', models.CharField(blank=True, default='#', max_length=200, null=True, verbose_name='Tik Tok')),
                ('telegram', models.CharField(blank=True, default='#', max_length=200, null=True, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, default='#', max_length=200, null=True, verbose_name='WhatsApp')),
                ('average_rating', models.FloatField(default=0, verbose_name='Média')),
                ('total_rating', models.IntegerField(default=0, verbose_name='Total de Avaliações')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'permissions': [('can_view_profile', 'Pode Ver Perfil'), ('can_change_profile', 'Pode Atualizar Perfil'), ('can_add_profile', 'Pode Adicionar Perfil'), ('can_delete_profile', 'Pode Deletar Perfil')],
            },
        ),
        migrations.CreateModel(
            name='BannersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banners', models.ImageField(upload_to='banners/', verbose_name='Imagem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners_profile', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentário')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='account.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(check=models.Q(('rating__range', (0, 5))), name='valid_rate'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'profile'), name='unique_rating'),
        ),
    ]
