# Generated by Django 5.0.3 on 2024-05-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rating_rating_valid_rate_rating_unique_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='average_rating',
            field=models.FloatField(default=0, verbose_name='Média'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_rating',
            field=models.IntegerField(default=0, verbose_name='Total de Avaliações'),
        ),
    ]
