# Generated by Django 5.0.3 on 2024-05-31 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_average_rating_profile_total_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banners', models.ImageField(upload_to='banners/', verbose_name='Imagem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners_profile', to='account.profile')),
            ],
        ),
    ]
