# Generated by Django 5.0.3 on 2024-12-19 17:57

import ckeditor.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('image_tarot', models.ImageField(upload_to='cards/', verbose_name='Imagem')),
                ('text_body', ckeditor.fields.RichTextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(choices=[('fas fa-wand', 'Paus'), ('fas fa-trophy', 'Cálice'), ('fas fa-sword', 'Espadas'), ('fas fa-coin', 'Moeda')], max_length=20, verbose_name='Ícone')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('name_corte', models.CharField(choices=[('Pajem de Paus', 'Pajem de Paus'), ('Cavaleiro de Paus', 'Cavaleiro de Paus'), ('Rainha de Paus', 'Rainha de Paus'), ('Rei de Paus', 'Rei de Paus'), ('Pajem de Copas', 'Pajem de Copas'), ('Cavaleiro de Copas', 'Cavaleiro de Copas'), ('Rainha de Copas', 'Rainha de Copas'), ('Rei de Copas', 'Rei de Copas'), ('Pajem de Espadas', 'Pajem de Espadas'), ('Cavaleiro de Espadas', 'Cavaleiro de Espadas'), ('Rainha de Espadas', 'Rainha de Espadas'), ('Rei de Espadas', 'Rei de Espadas'), ('Pajem de Ouros', 'Pajem de Ouros'), ('Cavaleiro de Ouros', 'Cavaleiro de Ouros'), ('Rainha de Ouros', 'Rainha de Ouros'), ('Rei de Ouros', 'Rei de Ouros')], max_length=20, unique=True, verbose_name='Nome')),
                ('image_corte', models.ImageField(upload_to='cards/', verbose_name='Imagem')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descrição')),
                ('key_word_minor', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Palavras Chave')),
            ],
            options={
                'ordering': ['name_corte'],
                'indexes': [models.Index(fields=['name_corte'], name='cards_corte_name_co_0c588b_idx')],
            },
        ),
        migrations.CreateModel(
            name='MajorArcana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_major_arcana', models.CharField(choices=[('0 - O Louco', '0 - O Louco'), ('1 - O Mago', '1 - O Mago'), ('2 - A Sacerdotisa', '2 - A Sacerdotisa'), ('3 - A Imperatriz', '3 - A Imperatriz'), ('4 - O Imperador', '4 - O Imperador'), ('5 - O Hierofante', '5 - O Hierofante'), ('6 - Os Amantes', '6 - Os Amantes'), ('7 - A Carruagem', '7 - A Carruagem'), ('8 - A Justiça', '8 - A Justiça'), ('9 - O Eremita', '9 - O Eremita'), ('10 - A Roda da Fortuna', '10 - A Roda da Fortuna'), ('11 - A Força', '11 - A Força'), ('12 - O Enforcado', '12 - O Enforcado'), ('13 - A Morte', '13 - A Morte'), ('14 - A Temperança', '14 - A Temperança'), ('15 - O Diabo', '15 - O Diabo'), ('16 - A Torre', '16 - A Torre'), ('17 - A Estrela', '17 - A Estrela'), ('18 - A Lua', '18 - A Lua'), ('19 - O Sol', '19 - O Sol'), ('20 - O Julgamento', '20 - O Julgamento'), ('21 - O Mundo', '21 - O Mundo')], max_length=30, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='Slug')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descrição')),
                ('image_major', models.ImageField(upload_to='cards/', verbose_name='Imagem')),
                ('key_word_major', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Palavras Chave')),
            ],
            options={
                'ordering': ['name_major_arcana'],
                'indexes': [models.Index(fields=['name_major_arcana'], name='cards_major_name_ma_428fe8_idx')],
            },
        ),
        migrations.CreateModel(
            name='MinorArcana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(choices=[('fas fa-wand', 'Paus'), ('fas fa-trophy', 'Cálice'), ('fas fa-sword', 'Espadas'), ('fas fa-coin', 'Moeda')], max_length=20, verbose_name='Ícone')),
                ('name_minor_arcana', models.CharField(choices=[('Às de Paus', 'Às de Paus'), ('Dois de Paus', 'Dois de Paus'), ('Três de Paus', 'Três de Paus'), ('Quatro de Paus', 'Quatro de Paus'), ('Cinco de Paus', 'Cinco de Paus'), ('Seis de Paus', 'Seis de Paus'), ('Sete de Paus', 'Sete de Paus'), ('Oito de Paus', 'Oito de Paus'), ('Nove de Paus', 'Nove de Paus'), ('Dez de Paus', 'Dez de Paus'), ('Às de Copas', 'Às de Copas'), ('Dois de Copas', 'Dois de Copas'), ('Três de Copas', 'Três de Copas'), ('Quatro de Copas', 'Quatro de Copas'), ('Cinco de Copas', 'Cinco de Copas'), ('Seis de Copas', 'Seis de Copas'), ('Sete de Copas', 'Sete de Copas'), ('Oito de Copas', 'Oito de Copas'), ('Nove de Copas', 'Nove de Copas'), ('Dez de Copas', 'Dez de Copas'), ('Às de Espadas', 'Às de Espadas'), ('Dois de Espadas', 'Dois de Espadas'), ('Três de Espadas', 'Três de Espadas'), ('Quatro de Espadas', 'Quatro de Espadas'), ('Cinco de Espadas', 'Cinco de Espadas'), ('Seis de Espadas', 'Seis de Espadas'), ('Sete de Espadas', 'Sete de Espadas'), ('Oito de Espadas', 'Oito de Espadas'), ('Nove de Espadas', 'Nove de Espadas'), ('Dez de Espadas', 'Dez de Espadas'), ('Às de Ouros', 'Às de Ouros'), ('Dois de Ouros', 'Dois de Ouros'), ('Três de Ouros', 'Três de Ouros'), ('Quatro de Ouros', 'Quatro de Ouros'), ('Cinco de Ouros', 'Cinco de Ouros'), ('Seis de Ouros', 'Seis de Ouros'), ('Sete de Ouros', 'Sete de Ouros'), ('Oito de Ouros', 'Oito de Ouros'), ('Nove de Ouros', 'Nove de Ouros'), ('Dez de Ouros', 'Dez de Ouros')], max_length=20, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descrição')),
                ('image_minor', models.ImageField(upload_to='cards/', verbose_name='Imagem')),
                ('key_word_minor', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Palavras Chave')),
            ],
            options={
                'ordering': ['name_minor_arcana'],
                'indexes': [models.Index(fields=['name_minor_arcana'], name='cards_minor_name_mi_4a5398_idx')],
            },
        ),
    ]
